# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-demo-2',
                'doc_host': 'https://ryanvance74.github.io',
                'git_url': 'https://github.com/ryanvance74/nbdev-demo-2',
                'lib_path': 'nbdev_demo_2'},
  'syms': {'nbdev_demo_2.core': {'nbdev_demo_2.core.foo': ('core.html#foo', 'nbdev_demo_2/core.py')}}}
